### ISSUE TITLE
Move asset-router's logic support detection to compile-time

### ISSUE THREAD

**Issue by sea212** [zeitgeistpm/zeitgeist#1198]
The goal of this issue is to improve the asset-router, such that trying to reserve or lock unsupported assets will result in a compilation error.

Currently the asset-router does check whether an asset supports reserves and locks during execution. This is a bad practice, as pallet which utilize the asset-router pallet don't know if the assets they are planning to reserve or lock support it at all.
